add Huaweicloud as supported list of clouds for testbed.
osism/testbed pull request #1563
Opened 2023-03-22 10:10 UTC by swaroopar

Hi, we tried to install the test bed on Huaweicloud EU region and it worked. So updating the documentation to reflect the same. 
Thank you.

2023-03-22 15:43 UTC, swaroopar commented
Hi Team, Could you please see if there is a possibility to restart the failing CI job? the failure does not seem to be coming from the changes in this PR. Thanks in advance.

2023-03-23 15:07 UTC, swaroopar commented
Hi Team, the job failed again. Can you please start it again?

2023-03-23 15:25 UTC, osfrickler requested changes
Thanks for your contribution, sadly the CI is a bit unstable currently. The failures are not related to your patch, so you can ignore them. Please see my comments below.

2023-03-23 15:25 UTC, osfrickler commented on doc/requirements.md
> +> * Regsistration is possible via https://www.huaweicloud.com/eu/
Registration

2023-03-23 16:53 UTC, swaroopar commented on terraform/environments/huaweicloud.tfvars
> +image                     = "Ubuntu 20.04 server 64bit"
updated.

2023-03-23 19:05 UTC, osfrickler approved these changes
thx, CI has some unrelated failures again, ignoring those

2023-03-23 19:05 UTC, merged