Feat/otc support1
osism/testbed pull request #594
Opened 2021-01-22 14:17 UTC by garloff

This PR includes:
* environment files for otc (working) and otc-physical (WIP)
* README.otc
* renaming of neutron.patch into neutron-az.patch (patch required on half of the clouds)
* new neutron-snat.patch (patch required for OTC)
* new docker-ansible-otc.patch (patch req. for OTC Ubuntu images)
All in the terraform directory of testbed.

2021-01-22 19:15 UTC, berendt requested changes

2021-01-22 19:15 UTC, berendt commented on terraform/README.otc
> +  network AZ hints
Solved with overrides (#595).  No longer required.

2021-01-22 19:15 UTC, berendt commented on terraform/README.otc
> +  mentioned patch).
Solved with overrides (#595).  No longer required.

2021-01-22 19:15 UTC, berendt commented on terraform/neutron-az.patch
> +Subject: Disable all availability zone hints for networking resources
Solved with overrides (#595).  No longer required.

2021-01-22 19:15 UTC, berendt commented on terraform/neutron-snat.patch
> +Subject: Enable SNAT on the router (for OTC)
Solved with overrides (#595).  No longer required.

2021-01-22 19:15 UTC, berendt commented on terraform/terraform-0.13.patch
> +thus this is only a patch and not integrated into the main branch.
Why? Makes no sense to me to enable per patch 0.13. We should always use the latest version of Terraform. This is also tested in the CI.

2021-01-22 19:15 UTC, berendt commented on terraform/manager.tf
> +  - "dpkg -r ansible || true"
Solved with #596. No longer required.

2021-01-22 19:15 UTC, berendt commented on terraform/nodes.tf
> +  - "dpkg -r ansible || true"
Solved with #596. No longer required.

2021-01-22 19:30 UTC, berendt commented on terraform/environment-otc.tfvars
> +availability_zone         = "eu-de-02"
Please move to environments/... (see #597).

2021-01-25 07:10 UTC, closed without merging

2021-01-26 07:25 UTC, garloff commented
Superceded by #601.